export { default as getHomeTopBanner } from './HomeTopBanner';
export { default as getAllCounts } from '../../Services/AllCounts';
export { default as getMissionVision } from '../../Services/MissionVision';
export { default as getCourses } from './Courses';
export { default as getActivitiesEvents } from './ActivitiesEvents';
export { default as getTestimonials } from './Testimonials';
export { default as getPartnerships } from './Partnerships';
export { default as getAppAdvertisement } from './AppAdvertisement';
export { default as getBlogs } from './Blogs';
